# created:    20260409 / alphabeit
# lastupdate: 20260421 / alphabeit

name: carconfigurator
version: 1.0
services:
  
  # mssql database; ubuntu based image
  # See also as ref https://hub.docker.com/r/microsoft/mssql-server/
  database:    
    image: mcr.microsoft.com/mssql/server:2025-latest
    expose:      
     - "1433"      
    restart: always    
    environment:      
      TZ: Europe/Berlin
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "!Password1234"
      MSSQL_PID: Express
      TrustServerCertificate: yes

  # create tables in database based upon code backend
  # run after database, before backend
  # See also as ref https://www.linkedin.com/pulse/solving-net-ef-core-migrations-docker-compose-cicd-pipelines-jamal-hialf
  migration:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    working_dir: /src
    volumes:
      - ./backend:/src
    environment:
      - DOTNET_CLI_HOME=/tmp
      - PATH=/tmp/.dotnet/tools:$PATH
    entrypoint: >
      sh -c "dotnet tool install --global dotnet-ef &&
            dotnet restore &&
            dotnet build &&
            dotnet ef migrations add InitialCreate &&
            dotnet ef database update"
    depends_on:
      - database
  
  # .NET Runtime
  # run backend (database interface and api server)
  # See Dockerfile "backend.dockerfile" for more infos.
  # See also as ref https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows&pivots=dotnet-10-0
  backend:    
    build:
      context: .
      dockerfile: backend.dockerfile
    expose:
      - "8080"
    restart: always    
    environment:      
      TZ: Europe/Berlin
    depends_on:
      - database
      - migration

  # using nginx as reservproxy; alpine based image
  reservproxy:    
    image: docker.io/nginx:alpine
    ports:      
     - "80:80"      
     - "443:443"    
    volumes:
     - ./reservproxy/nginx.conf:/etc/nginx/nginx.conf:ro
    # - ./reservproxy/nginxsecure.conf:/etc/nginx/nginx.conf:ro     
    # - ./reservproxy/certs/:/etc/nginx/ssl/:ro  
    restart: always    
    environment:      
      TZ: Europe/Berlin
    depends_on:
      - backend
      #- frontends

  # vue.js applications; alpine based image
  frontends:    
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
     - "81:80"
    restart: always    
    environment:      
      TZ: Europe/Berlin
